#!/usr/bin/env bash
# 008-content-skill-rename — /ztn:check-content → /ztn:content reshape.
#
# Engine 0.35.0 reshapes the content skill: the folder
# `integrations/claude-code/skills/ztn-check-content/` becomes `ztn-content/`,
# the skill gains `--maintain` (the draft-maintainer) + `--draft` modes, and the
# `content-pipeline-reminder` is retired (the maintainer self-surfaces). The new
# `ztn-content/` folder + the CONTENT_MAP view template + the content ledger
# template arrive via `/ztn:update` engine sync; this migration cleans up the
# stale old-name artifacts the sync leaves behind and seeds the live ledger.
#
# This script:
#   1. removes the stale `ztn-check-content/` skill folder (sync adds the new
#      folder but never deletes the old one)
#   2. drops the stale project-level `.claude/skills/ztn-check-content` symlink
#      and adds `.claude/skills/ztn-content` if missing
#   3. drops the stale user-level `~/.claude/skills/ztn-check-content` symlink
#      (re-running install.sh recreates the ztn-content one)
#   4. seeds the live content ledger from its template if missing
#
# Owner data is never deleted: a pre-existing `CONTENT_OVERVIEW.md` (the old
# view) is left in place and only reported — the new `CONTENT_MAP.md` is a
# distinct file regenerated by /ztn:maintain.
#
# Idempotent: re-running on a migrated repo is a no-op.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SKILLS="$REPO_ROOT/integrations/claude-code/skills"
PROJ_SKILLS="$REPO_ROOT/.claude/skills"
ZTN="$REPO_ROOT/zettelkasten"
STATE="$ZTN/_system/state"

# 1. Remove stale old-name skill folder.
if [[ -d "$SKILLS/ztn-check-content" ]]; then
    rm -rf "$SKILLS/ztn-check-content"
    echo "removed stale skill folder: ztn-check-content/"
fi

# 2. Project-level symlink.
if [[ -L "$PROJ_SKILLS/ztn-check-content" || -e "$PROJ_SKILLS/ztn-check-content" ]]; then
    rm -f "$PROJ_SKILLS/ztn-check-content"
    echo "removed stale project symlink: .claude/skills/ztn-check-content"
fi
if [[ -d "$SKILLS/ztn-content" && ! -e "$PROJ_SKILLS/ztn-content" ]]; then
    ( cd "$PROJ_SKILLS" && ln -s "../../integrations/claude-code/skills/ztn-content" "ztn-content" )
    echo "added project symlink: .claude/skills/ztn-content"
fi

# 3. User-level symlink (install.sh recreates the ztn-content one).
USER_SKILLS="${CLAUDE_HOME:-$HOME/.claude}/skills"
if [[ -L "$USER_SKILLS/ztn-check-content" || -e "$USER_SKILLS/ztn-check-content" ]]; then
    rm -f "$USER_SKILLS/ztn-check-content"
    echo "removed stale user symlink: ~/.claude/skills/ztn-check-content (re-run install.sh)"
fi

# 4. Seed the live content ledger from template if missing.
LEDGER_LIVE="$STATE/content-pipeline-state.json"
LEDGER_TPL="$STATE/content-pipeline-state.template.json"
if [[ ! -f "$LEDGER_LIVE" && -f "$LEDGER_TPL" ]]; then
    cp "$LEDGER_TPL" "$LEDGER_LIVE"
    echo "seeded content ledger: content-pipeline-state.json"
fi

# Report (do not delete) a stale old view.
if [[ -f "$ZTN/_system/views/CONTENT_OVERVIEW.md" ]]; then
    echo "note: legacy CONTENT_OVERVIEW.md found — superseded by CONTENT_MAP.md; remove by hand if desired."
fi

echo "008-content-skill-rename: done. Re-run integrations/claude-code/install.sh to refresh user symlinks."
