#!/usr/bin/env bash
# migration-kind: heal
# 029-refresh-vault-help — un-freeze the Obsidian help docs in the vault.
#
# `<vault>/5_meta/help/` holds four copies of engine docs — the guide, the view
# presets, the privacy note and the changelog. They were seeded copy-if-missing,
# so every clone's copies froze at the moment that clone was installed: the
# seeder skipped them forever after, and the updater did not touch them at all.
# Measured on the authoring instance before this change: the changelog was 217
# lines behind its source and the privacy note 122, and one copy still carried a
# real person's name where the engine source had used a placeholder for months.
# Nothing reported any of it, because a stale doc looks exactly like a current
# one.
#
# From this version they are DERIVED: regenerated by the seeder, and refreshed
# by `sync_engine.sh` after every update. This migration is the transition —
# it protects whatever is there now, then hands over to the same seeder the
# steady state uses.
#
# WHY IT BACKS UP FIRST. Until now these files were promised preservation, so an
# edit someone made under that promise is indistinguishable from stale generated
# content — `cmp` sees only "differs". Discarding it silently would break the
# contract that was in force when the edit was made. So anything that differs is
# copied aside ONCE, into a dot-directory Obsidian does not display, and named
# in the output. The steady state needs no such backup: from here on the file is
# only ever engine-generated, exactly like every other derived view.
#
# Kind is `heal`: a failed refresh leaves the clone merely still stale, which is
# not dangerous to continue past. It is recorded `partial` and retried on the
# next update — which is the whole reason the exits below are honest rather than
# a blanket `exit 0`. A migration that reports success while doing nothing is
# recorded as applied and never runs again.
#
# Idempotent: with the copies already current, it backs up nothing and the
# seeder reports "up to date".

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SEEDER="$REPO_ROOT/integrations/obsidian/seed.sh"
VAULT="${MINDER_ZTN_BASE:-$REPO_ROOT/zettelkasten}"
HELP="$VAULT/5_meta/help"
BACKUP="$HELP/.pre-refresh-backup"

if [ ! -f "$SEEDER" ]; then
  echo "029: seeder missing at $SEEDER — cannot refresh; will retry next update" >&2
  exit 1
fi

if [ ! -d "$VAULT/_system" ]; then
  echo "029: $VAULT is not a ZTN base (no _system/) — nothing to refresh" >&2
  exit 1
fi

# --- One-time protection of whatever is there now ---
saved=0
if [ -d "$HELP" ]; then
  # bash 3.2: no associative arrays.
  pairs="$REPO_ROOT/integrations/obsidian/guide.md|$HELP/guide.md
$REPO_ROOT/integrations/obsidian/views.md|$HELP/views.md
$REPO_ROOT/docs/privacy.md|$HELP/privacy.md
$REPO_ROOT/docs/CHANGELOG.md|$HELP/CHANGELOG.md"
  while IFS='|' read -r src dst; do
    [ -n "$src" ] || continue
    [ -f "$dst" ] || continue
    [ -f "$src" ] || continue
    cmp -s "$src" "$dst" && continue
    mkdir -p "$BACKUP"
    # Never overwrite an earlier backup: a re-run must not bury the original
    # under a copy of the already-refreshed file.
    [ -f "$BACKUP/$(basename "$dst")" ] && continue
    cp "$dst" "$BACKUP/$(basename "$dst")"
    saved=$((saved + 1))
  done <<PAIRS
$pairs
PAIRS
fi

if [ "$saved" -gt 0 ]; then
  echo "029: $saved help doc(s) differed and were copied to $BACKUP"
  echo "029: they are engine documents from now on — delete that directory once you have looked."
fi

# Delegate rather than restate: the copy rule, the atomic replace and the source
# list all live in the seeder. A migration that re-implemented them would become
# the older of the two the moment the seeder moved.
bash "$SEEDER" --refresh-help
