#!/usr/bin/env python3
"""ZTN lint Scan A.9 — hub frontmatter integrity (ARCH-B).

Validates the ARCH-B hub schema:
  - hub_kind ∈ {project, trajectory, domain} (default project)
  - chronological_map_mode ∈ {derived, curated} (default curated)
  - derived hubs must carry AUTO-GENERATED markers in body
  - excluded_from_map / excluded_from_map_reasons same length
  - excluded record-ids must resolve in the corpus
  - trajectory/domain hubs with mode=derived flagged as policy violation

Output: JSONL on stdout, one event per violation. Exit 0 always.

Informational only; no autofix in initial ship. CLARIFICATIONs surface
for owner review.

Usage:
    python3 lint_hub_integrity.py [--root <path>]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from _common import read_frontmatter, repo_root


VALID_HUB_KINDS = frozenset({"project", "trajectory", "domain"})
VALID_MAP_MODES = frozenset({"derived", "curated"})

AUTO_BEGIN_RE = re.compile(r"<!-- AUTO-GENERATED by render_hub_maps\.py")
AUTO_END_RE = re.compile(r"<!-- /AUTO-GENERATED -->")

NOTE_SCOPES = ("_records/", "1_projects/", "2_areas/", "3_resources/", "4_archive/", "5_meta/mocs/")


def _emit(event: dict) -> None:
    sys.stdout.write(json.dumps(event, ensure_ascii=False) + "\n")


def _build_id_index(root: Path) -> set[str]:
    """Scan all notes once to build a set of valid record-ids."""
    ids: set[str] = set()
    for prefix in NOTE_SCOPES:
        base = root / prefix
        if not base.exists():
            continue
        for path in base.rglob("*.md"):
            fm_body = read_frontmatter(path)
            if fm_body is None:
                continue
            fm, _ = fm_body
            note_id = fm.get("id")
            if note_id:
                ids.add(str(note_id))
            else:
                ids.add(path.stem)
    return ids


def _scan_hub(path: Path, valid_ids: set[str]) -> None:
    fm_body = read_frontmatter(path)
    if fm_body is None:
        return
    fm, body = fm_body

    hub_id = fm.get("id") or path.stem
    rel = str(path.relative_to(path.parents[2] if path.parents else path))
    base_event = {
        "scan": "A.9",
        "hub_id": hub_id,
        "path": str(path),
    }

    # 1. hub_kind value
    hub_kind = fm.get("hub_kind")
    if hub_kind is None:
        hub_kind = "project"
    elif hub_kind not in VALID_HUB_KINDS:
        _emit({**base_event,
               "kind": "hub-kind-unknown",
               "severity": "weak",
               "value": str(hub_kind),
               "reason": (
                   f"hub_kind={hub_kind!r} is not in "
                   f"{sorted(VALID_HUB_KINDS)}."
               ),
               "to_resolve": (
                   "Set hub_kind to project / trajectory / domain "
                   "based on PROCESSING_PRINCIPLES §9 hub-kind table."
               )})
        # don't return — keep checking other fields with default
        hub_kind = "project"

    # 2. chronological_map_mode value
    mode = fm.get("chronological_map_mode")
    if mode is None:
        mode = "curated"
    elif mode not in VALID_MAP_MODES:
        _emit({**base_event,
               "kind": "hub-chronological-map-mode-unknown",
               "severity": "weak",
               "value": str(mode),
               "reason": (
                   f"chronological_map_mode={mode!r} is not in "
                   f"{sorted(VALID_MAP_MODES)}."
               ),
               "to_resolve": "Set to derived OR curated."})
        mode = "curated"

    # 3. Derived mode marker presence
    if mode == "derived":
        has_begin = bool(AUTO_BEGIN_RE.search(body))
        has_end = bool(AUTO_END_RE.search(body))
        if not (has_begin and has_end):
            _emit({**base_event,
                   "kind": "hub-derived-map-markers-missing",
                   "severity": "weak",
                   "has_begin": has_begin,
                   "has_end": has_end,
                   "reason": (
                       "Hub has chronological_map_mode: derived but "
                       "body lacks AUTO-GENERATED markers — render has "
                       "not run yet, or markers were hand-deleted."
                   ),
                   "to_resolve": (
                       "Run `python3 _system/scripts/render_hub_maps.py "
                       f"--apply --hub {hub_id}` "
                       "OR run `/ztn:maintain` (Step 7.7 covers this)."
                   )})

    # 4. Excluded-list integrity
    excl_ids = fm.get("excluded_from_map") or []
    excl_reasons = fm.get("excluded_from_map_reasons") or []
    if isinstance(excl_ids, list) and isinstance(excl_reasons, list):
        if len(excl_ids) != len(excl_reasons):
            _emit({**base_event,
                   "kind": "hub-excluded-arrays-length-mismatch",
                   "severity": "weak",
                   "ids_length": len(excl_ids),
                   "reasons_length": len(excl_reasons),
                   "reason": (
                       f"excluded_from_map ({len(excl_ids)}) and "
                       f"excluded_from_map_reasons ({len(excl_reasons)}) "
                       "must have the same length — index alignment."
                   ),
                   "to_resolve": (
                       "Pad shorter array with placeholder reasons OR "
                       "trim longer array. Each excluded id needs a "
                       "rationale at the same index."
                   )})
        for rid in excl_ids:
            if str(rid) not in valid_ids:
                _emit({**base_event,
                       "kind": "hub-excluded-id-unresolvable",
                       "severity": "weak",
                       "excluded_id": str(rid),
                       "reason": (
                           f"excluded_from_map entry `{rid}` does not "
                           "resolve to any record / knowledge note "
                           "in the corpus."
                       ),
                       "to_resolve": (
                           f"Verify `{rid}`; either fix the slug, "
                           "drop the entry (record was renamed/deleted), "
                           "or restore the missing record."
                       )})

    # 5. Trajectory / domain with derived mode
    if hub_kind in ("trajectory", "domain") and mode == "derived":
        _emit({**base_event,
               "kind": "hub-trajectory-derived-policy",
               "severity": "weak",
               "hub_kind": hub_kind,
               "reason": (
                   f"hub_kind={hub_kind} with chronological_map_mode: "
                   "derived. Trajectories and domains are intentionally "
                   "curated (PROCESSING_PRINCIPLES §9 Q4 default) — "
                   "narrative arcs typically don't fit auto-derivation."
               ),
               "to_resolve": (
                   "Either set chronological_map_mode: curated OR "
                   "explicitly confirm derived is the right choice "
                   "(may be valid for some domain hubs with strict "
                   "membership semantics)."
               )})


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=None)
    args = parser.parse_args(argv)

    root = args.root or repo_root() / "zettelkasten"
    if not root.exists():
        print(f"ERROR: root does not exist: {root}", file=sys.stderr)
        return 1

    mocs = root / "5_meta" / "mocs"
    if not mocs.exists():
        print("ERROR: 5_meta/mocs not found", file=sys.stderr)
        return 1

    valid_ids = _build_id_index(root)

    for hub_path in sorted(mocs.glob("hub-*.md")):
        _scan_hub(hub_path, valid_ids)

    return 0


if __name__ == "__main__":
    sys.exit(main())
