#!/usr/bin/env python3
"""Render `_system/views/ROLES.md` — the roles registry projection.

Deterministic projection over every role instance under `_system/roles/`: one
row per role with id, name, its ordered `parts` (each `{id, kind}` with a
per-part item/summary count read from `parts/{part_id}.json`), cadence, status,
and last successful run date (from `roles-runs.jsonl`). A role is a COMPOSITE of
parts; the row lists every part in declared order with its own count. Owner
data — excluded from the shipped skeleton; the file is rendered whole (no owner
zone, no volatile timestamp), so re-running with unchanged inputs produces a
byte-identical file.

Discovery is a glob (`roles_common.discover_role_ids`). A role directory whose
`config.yml` fails to load is dropped from the table and surfaced in a
`## Skipped` section — the engine surfaces the problem, it never guesses a
projection nor crashes on one bad role. Under the composite model a `config.yml`
that fails to load INCLUDES one naming a `part.kind` with no installed plugin
(the loader fail-closes) and any residual v1 scalar-`archetype` config (the
scalar field is removed) — both land in `## Skipped` with the loader's reason.

Runs unattended inside `/ztn:maintain` (post-loop `--apply` step). `main()`
never raises: any unexpected failure degrades to `{"ok": false, "reason": …}`
on stdout and returns 0, so a malformed input can never abort the maintain
pipeline.

Usage:
    python3 render_roles_registry.py             # print unified diff, no write
    python3 render_roles_registry.py --apply     # write ROLES.md atomically
    python3 render_roles_registry.py --check      # exit 3 if it WOULD change
    python3 render_roles_registry.py --dry-run    # print rendered document
    python3 render_roles_registry.py --root <ztn-base>
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from _common import repo_root, views_dir

from roles_common import (
    PartSpec,
    RoleConfig,
    discover_role_ids,
    import_archetype,
    last_successful_run,
    load_role_config,
    part_state_path,
)

VIEW_FILENAME = "ROLES.md"

AUTO_NOTE = (
    "<!-- AUTO-GENERATED by render_roles_registry.py — do not hand-edit. "
    "Re-run /ztn:maintain to refresh. -->"
)

DASH = "—"


# -----------------------------------------------------------------------------
# Per-part state summaries (a projection reads known part-kind state files)
# -----------------------------------------------------------------------------

@dataclass(frozen=True)
class StateSummary:
    """Item-count projection of one part's state.

    `breakdown` is a pre-ordered list of `(label, count)` pairs — the summarizer
    owns the ordering, so the cell renderer stays part-kind-neutral. `staged`
    counts a frozen cold-start draft not yet approved (§6 per-part staging).
    """
    total: int
    breakdown: tuple[tuple[str, int], ...]
    staged: int


@dataclass(frozen=True)
class PartSummary:
    """One rendered part of a role: its id, kind, and count summary (or None).

    `summary` is None when the part's kind has no registered summarizer (not
    built yet) or its state file is absent / unreadable — the projection shows
    DASH rather than a guessed count. `part_id` + `kind` come from the loaded
    `config.parts[]` and are always present.
    """
    part_id: str
    kind: str
    summary: StateSummary | None


def _summary_from_plugin(kind: str, state: dict) -> StateSummary | None:
    """Dispatch a part's count-summary through its plugin's `registry_summary` hook.

    The projection reads ONLY the plain dict a part plugin returns
    (`{total, breakdown, staged}`) — never a part-kind's internal state shape — so
    it stays part-kind-neutral, exactly like the writer. A plugin without the hook,
    or one whose hook errors on a corrupt state, degrades to None (DASH) rather than
    crashing the unattended maintain step (honest: counts unavailable, not guessed).
    A new part-kind gains a registry cell by implementing the hook — nothing here
    changes. A kind whose PLUGIN does not load never reaches this path: the role
    fail-closes at `load_role_config` and lands in `## Skipped`.
    """
    try:
        fn = getattr(import_archetype(kind), "registry_summary", None)
        if fn is None:
            return None
        raw = fn(state)
    except Exception:  # noqa: BLE001 — a summarizer must never crash the registry
        return None
    if not isinstance(raw, dict):
        return None
    breakdown = tuple(
        (str(b[0]), int(b[1]))
        for b in (raw.get("breakdown") or [])
        if isinstance(b, (list, tuple)) and len(b) == 2
    )
    try:
        return StateSummary(
            total=int(raw.get("total", 0)),
            breakdown=breakdown,
            staged=int(raw.get("staged", 0)),
        )
    except (TypeError, ValueError):
        return None


def _read_json_dict(path: Path) -> dict | None:
    """Read a JSON object from `path`, or None (missing / unreadable / non-object).

    Read-only and fully tolerant — the projection never writes part state and
    must not crash on a state file mid-write or hand-damaged.
    """
    if not path.is_file():
        return None
    try:
        obj = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, ValueError):
        return None
    return obj if isinstance(obj, dict) else None


def part_summary(role_id: str, part: PartSpec, base: Path | None = None) -> PartSummary:
    """Count-summary for one part of a role.

    `summary` is None when: the part's kind has no `registry_summary` hook (not
    built yet), or its `parts/{part_id}.json` is absent / unreadable (e.g. the
    role was defined but never ticked, or the part is still cold-start-armed).
    Either way the projection shows DASH for that part rather than a guessed
    count. `part_id` / `kind` always come straight from the loaded config.
    """
    state = _read_json_dict(part_state_path(role_id, part.id, base))
    if state is None:
        return PartSummary(part_id=part.id, kind=part.kind, summary=None)
    return PartSummary(
        part_id=part.id, kind=part.kind, summary=_summary_from_plugin(part.kind, state)
    )


# -----------------------------------------------------------------------------
# Row model + build
# -----------------------------------------------------------------------------

@dataclass(frozen=True)
class RoleRow:
    """One rendered registry row (projection of one role instance).

    `parts` is the role's ordered `config.parts[]` projected to `PartSummary` —
    every part in declared order with its own count, so the row shows the
    composite shape and per-part counts together.
    """
    id: str
    name: str
    parts: tuple[PartSummary, ...]
    cadence: str
    status: str
    last_run: str | None  # YYYY-MM-DD, or None when the role never ran


def _format_cadence(cfg: RoleConfig) -> str:
    """Human-readable cadence + anchor (`weekly (monday)`, `monthly (day 15)`)."""
    cadence = cfg.cadence
    anchor = cfg.cadence_anchor
    if cadence == "daily":
        return "daily"
    if cadence in ("weekly", "biweekly"):
        return f"{cadence} ({anchor})"
    if cadence == "monthly":
        return f"monthly (day {anchor})"
    return cadence


def _last_run_date(run: Any) -> str | None:
    """Extract the YYYY-MM-DD of a run entry's `run_at`, or None."""
    if not isinstance(run, dict):
        return None
    run_at = run.get("run_at")
    if isinstance(run_at, str) and run_at.strip():
        return run_at.strip()[:10]
    return None


def build_rows(base: Path | None = None) -> tuple[list[RoleRow], list[dict]]:
    """Discover roles and build (rows, skipped).

    `rows` are sorted by role id (from `discover_role_ids`). `skipped` holds one
    `{"dir", "reason"}` record per role whose config could not be loaded — the
    drop-and-surface path: one bad role never aborts the registry, and its
    reason is rendered so the owner can fix it. A config naming an unresolvable
    `part.kind`, or a residual v1 scalar-`archetype` config, fail-close through
    `load_role_config` and land here with the loader's reason.
    """
    rows: list[RoleRow] = []
    skipped: list[dict] = []
    for role_id in discover_role_ids(base):
        try:
            cfg = load_role_config(role_id, base)
            parts = tuple(part_summary(cfg.id, p, base) for p in cfg.parts)
            rows.append(
                RoleRow(
                    id=cfg.id,
                    name=cfg.name or cfg.id,
                    parts=parts,
                    cadence=_format_cadence(cfg),
                    status=cfg.status,
                    last_run=_last_run_date(last_successful_run(role_id, base)),
                )
            )
        except Exception as exc:  # noqa: BLE001 — drop-and-surface, never crash the registry
            skipped.append({"dir": role_id, "reason": f"{type(exc).__name__}: {exc}"})
    return rows, skipped


# -----------------------------------------------------------------------------
# Render
# -----------------------------------------------------------------------------

def _cell(text: Any) -> str:
    """Escape a value for a markdown table cell (pipes, newlines)."""
    return str(text).replace("|", "\\|").replace("\r", " ").replace("\n", " ").strip()


def _format_items_cell(summary: StateSummary | None) -> str:
    """Render one part's count: total, non-zero breakdown, cold-start staging."""
    if summary is None:
        return DASH
    cell = str(summary.total)
    if summary.breakdown:
        inner = " · ".join(f"{label} {count}" for label, count in summary.breakdown)
        cell = f"{cell} ({inner})"
    if summary.staged:
        cell = f"{cell} · cold-start {summary.staged} staged"
    return cell


def _format_parts_cell(parts: tuple[PartSummary, ...]) -> str:
    """Render the Parts cell: `part (kind): <count>` per part, joined by `; `.

    Lists every part in declared order so the composite shape and per-part counts
    read together; a part whose count is unavailable shows DASH. Parts are joined
    with `; ` (the per-part count itself uses ` · `, so the two separators never
    collide). A role always loads with at least one part; an empty tuple degrades
    to DASH defensively.
    """
    if not parts:
        return DASH
    return "; ".join(
        f"{ps.part_id} ({ps.kind}): {_format_items_cell(ps.summary)}" for ps in parts
    )


def render_document(rows: list[RoleRow], skipped: list[dict]) -> str:
    """Render the whole ROLES.md document (ends with exactly one newline)."""
    lines: list[str] = [
        "# Roles Registry",
        "",
        AUTO_NOTE,
        "",
        "_Deterministic projection of role instances under `_system/roles/`. "
        "Each role is a composite of ordered parts; the Parts column lists every "
        "part with its own count. Owner data — excluded from the shipped "
        "skeleton. Re-run `/ztn:maintain` to refresh._",
        "",
    ]

    if not rows:
        if skipped:
            lines.append("_No loadable roles._")
        else:
            lines.append("_No roles defined yet. Create one with `/ztn:role:add`._")
        lines.append("")
    else:
        lines.append("## Roles")
        lines.append("")
        lines.append("| Role | Name | Parts | Cadence | Status | Last run |")
        lines.append("|---|---|---|---|---|---|")
        for row in rows:
            lines.append(
                f"| {_cell(row.id)} | {_cell(row.name)} "
                f"| {_cell(_format_parts_cell(row.parts))} "
                f"| {_cell(row.cadence)} | {_cell(row.status)} "
                f"| {row.last_run or DASH} |"
            )
        lines.append("")

    if skipped:
        lines.append("## Skipped (malformed or unreadable config)")
        lines.append("")
        lines.append(
            "_These role directories hold a `config.yml` that failed to load. "
            "Fix or remove them — the engine surfaces the problem rather than "
            "guessing a projection._"
        )
        lines.append("")
        lines.append("| Directory | Reason |")
        lines.append("|---|---|")
        for entry in skipped:
            lines.append(
                f"| {_cell(entry.get('dir', DASH))} | {_cell(entry.get('reason', DASH))} |"
            )
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


# -----------------------------------------------------------------------------
# I/O helpers (atomic, LF-forced for cross-platform determinism)
# -----------------------------------------------------------------------------

def _read_current(path: Path) -> str:
    """Read the on-disk view (universal-newline), or "" when absent/unreadable."""
    if not path.is_file():
        return ""
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return ""


def _atomic_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with open(tmp, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    tmp.replace(path)


def _unified_diff(old: str, new: str, name: str) -> str:
    return "".join(
        difflib.unified_diff(
            old.splitlines(keepends=True),
            new.splitlines(keepends=True),
            fromfile=f"a/{name}",
            tofile=f"b/{name}",
            n=2,
        )
    )


# -----------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root", type=Path, default=None,
        help="ZTN base path (the zettelkasten dir; defaults to repo_root() / ZTN_BASE).",
    )
    parser.add_argument(
        "--apply", action="store_true",
        help="write ROLES.md atomically (used by /ztn:maintain). Without it, only a diff prints.",
    )
    parser.add_argument(
        "--check", action="store_true",
        help="exit 3 if ROLES.md would change; never write (CI gate).",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="print the rendered document to stdout; never write.",
    )
    args = parser.parse_args(argv)

    try:
        base = args.root if args.root is not None else repo_root()
        view_path = views_dir(base) / VIEW_FILENAME

        rows, skipped = build_rows(base)
        rendered = render_document(rows, skipped)
        current = _read_current(view_path)
        would_change = rendered != current

        result = {
            "ok": True,
            "changed": would_change,
            "roles": len(rows),
            "skipped": len(skipped),
            "path": view_path.name,
        }

        if args.dry_run:
            sys.stdout.write(rendered)
            return 0

        if args.check:
            print(json.dumps(result, ensure_ascii=False))
            return 3 if would_change else 0

        if args.apply:
            if would_change:
                _atomic_write(view_path, rendered)
            print(json.dumps(result, ensure_ascii=False))
            print(
                f"render_roles_registry: {len(rows)} role(s), {len(skipped)} skipped, "
                f"{'updated' if would_change else 'no change'}",
                file=sys.stderr,
            )
            return 0

        # default: unified diff to stdout (pipeable), machine summary to stderr
        if would_change:
            sys.stdout.write(_unified_diff(current, rendered, VIEW_FILENAME))
        print(json.dumps(result, ensure_ascii=False), file=sys.stderr)
        return 0

    except Exception as exc:  # noqa: BLE001 — unattended maintain step must never crash
        print(
            json.dumps(
                {
                    "ok": False,
                    "changed": False,
                    "reason": f"unexpected: {type(exc).__name__}: {exc}",
                },
                ensure_ascii=False,
            )
        )
        print(
            f"render_roles_registry: skipped — unexpected {type(exc).__name__}: {exc}",
            file=sys.stderr,
        )
        return 0


if __name__ == "__main__":
    sys.exit(main())
