#!/usr/bin/env python3
"""ARCH-B — render derived chronological-map sections in hubs.

For each hub with `chronological_map_mode: derived`:
  1. Find all records / knowledge notes where `projects:` contains the
     hub's project ID (slug after `hub-` prefix).
  2. Filter out records listed in hub's `excluded_from_map`.
  3. Sort by record.created (chronological).
  4. Render a markdown table «Дата | Заметка | Тип | Что произошло».
  5. Append «Excluded from map (editorial)» table if exclusion list non-empty.
  6. Replace the AUTO-GENERATED block in hub body (or insert if first run).

Idempotent — re-running produces byte-identical output unless source data
changed. Pure deterministic — no LLM in the loop.

Hubs with `chronological_map_mode: curated` (or absent: default `curated`
for backward-compat) are SKIPPED. Those keep their hand-curated maps.

Usage:
    python3 render_hub_maps.py [--root <path>] [--apply] [--hub <hub-id>]

When run without `--apply`, prints proposed changes to stdout (unified
diff per hub). With `--apply`, writes changes to disk.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from pathlib import Path

from _common import read_frontmatter, write_frontmatter, repo_root


AUTO_BEGIN = "<!-- AUTO-GENERATED by render_hub_maps.py — do not hand-edit between markers -->"
AUTO_END = "<!-- /AUTO-GENERATED -->"

AUTO_BLOCK_RE = re.compile(
    re.escape(AUTO_BEGIN) + r".*?" + re.escape(AUTO_END),
    re.DOTALL,
)

# Anchor for first-run insertion: replace the existing «## Хронологическая
# карта» section (header + body up to next `## ` or end of file).
LEGACY_MAP_RE = re.compile(
    r"^## Хронологическая карта.*?(?=^## (?!Хронологическая)|\Z)",
    re.MULTILINE | re.DOTALL,
)

SCOPE_INCLUDE: tuple[str, ...] = (
    "_records/",
    "1_projects/",
    "2_areas/",
    "3_resources/",
    "4_archive/",
)


def _hub_project_id(hub_path: Path) -> str:
    return hub_path.stem.removeprefix("hub-")


def _iter_member_notes(root: Path, project_id: str):
    """Yield (path, frontmatter) for all notes whose `projects:` contains
    project_id."""
    for prefix in SCOPE_INCLUDE:
        base = root / prefix
        if not base.exists():
            continue
        for path in base.rglob("*.md"):
            fm_body = read_frontmatter(path)
            if fm_body is None:
                continue
            fm, _ = fm_body
            projects = fm.get("projects") or []
            if not isinstance(projects, list):
                continue
            if project_id in projects:
                yield path, fm


def _kind_label(fm: dict) -> str:
    """Display label for «Тип» column."""
    if fm.get("kind"):
        return str(fm["kind"])
    types = fm.get("types") or []
    if isinstance(types, list) and types:
        return str(types[0])
    layer = fm.get("layer")
    if layer:
        return str(layer)
    return "—"


def _summary(fm: dict) -> str:
    """«Что произошло» column. Fallback chain: description → title → id."""
    for key in ("description", "title"):
        v = fm.get(key)
        if v and isinstance(v, str) and v.strip():
            # Strip outer quotes and truncate overly long descriptions
            text = v.strip().rstrip(".")
            if len(text) > 120:
                text = text[:117] + "…"
            return text
    return str(fm.get("id") or "—")


def _link_text(fm: dict) -> str:
    """Wikilink with display title fallback."""
    note_id = fm.get("id")
    title = fm.get("title")
    if not note_id:
        return "—"
    if title and isinstance(title, str) and title.strip():
        # Strip outer quotes from title
        clean = title.strip().strip("'\"")
        # Truncate for table readability
        if len(clean) > 80:
            clean = clean[:77] + "…"
        return f"[[{note_id}|{clean}]]"
    return f"[[{note_id}]]"


def _format_date(value) -> str:
    """ISO date as YYYY-MM-DD; tolerant of various input types."""
    if value is None:
        return "—"
    s = str(value).strip()
    # Take first 10 chars if it looks like ISO datetime
    return s[:10] if len(s) >= 10 else s


def _escape_table_cell(text: str) -> str:
    """Escape pipe characters that would break table parsing."""
    return text.replace("|", "\\|")


def _render_block(members: list[tuple[Path, dict]],
                  excluded_set: set[str],
                  excluded_reasons: list[str],
                  excluded_ids: list[str]) -> str:
    """Render the AUTO-GENERATED block content (everything between markers,
    exclusive of the markers themselves)."""
    # Filter out excluded
    visible = [
        (p, fm) for p, fm in members
        if str(fm.get("id") or p.stem) not in excluded_set
    ]
    # Sort by created, stable
    visible.sort(key=lambda pf: (str(pf[1].get("created") or ""), pf[1].get("id") or ""))

    lines: list[str] = []
    lines.append("## Хронологическая карта (derived)")
    lines.append("")
    lines.append(f"_Auto-generated from {len(visible)} member records — "
                 f"do not hand-edit between markers. "
                 f"Re-run `/ztn:maintain` to refresh._")
    lines.append("")
    if not visible:
        lines.append("_(no member records yet — nothing to derive)_")
    else:
        lines.append("| Дата | Заметка | Тип | Что произошло |")
        lines.append("|------|---------|-----|---------------|")
        for path, fm in visible:
            date = _format_date(fm.get("created"))
            link = _escape_table_cell(_link_text(fm))
            kind = _escape_table_cell(_kind_label(fm))
            summary = _escape_table_cell(_summary(fm))
            lines.append(f"| {date} | {link} | {kind} | {summary} |")

    if excluded_ids:
        lines.append("")
        lines.append("### Excluded from map (editorial)")
        lines.append("")
        lines.append("_Records that match this hub's project but were "
                     "explicitly excluded by curator. Edit "
                     "`excluded_from_map` in hub frontmatter to manage._")
        lines.append("")
        lines.append("| Record | Reason |")
        lines.append("|--------|--------|")
        for i, rid in enumerate(excluded_ids):
            reason = excluded_reasons[i] if i < len(excluded_reasons) else "—"
            lines.append(f"| [[{rid}]] | {_escape_table_cell(reason)} |")

    return "\n".join(lines)


def _replace_auto_block(body: str, block_content: str) -> tuple[str, str]:
    """Insert/replace AUTO-GENERATED block in body. Returns (new_body, mode).
    Mode is one of: 'replaced', 'inserted-from-legacy', 'appended'."""
    full_block = f"{AUTO_BEGIN}\n{block_content}\n{AUTO_END}"

    # Mode 1: existing AUTO-GENERATED block — replace in place
    if AUTO_BLOCK_RE.search(body):
        return AUTO_BLOCK_RE.sub(full_block, body, count=1), "replaced"

    # Mode 2: legacy «## Хронологическая карта» section — replace
    if LEGACY_MAP_RE.search(body):
        # Preserve trailing blank line semantics: legacy match captures up
        # to next `## ` header (exclusive). Our block doesn't end with a
        # newline; ensure we keep the same separator.
        new_body = LEGACY_MAP_RE.sub(full_block + "\n\n", body, count=1)
        return new_body, "inserted-from-legacy"

    # Mode 3: no anchor — append at end of body
    sep = "\n\n" if not body.endswith("\n") else "\n"
    return body + sep + full_block + "\n", "appended"


def _render_hub(hub_path: Path, root: Path) -> dict | None:
    """Return event dict or None if hub is skipped."""
    fm_body = read_frontmatter(hub_path)
    if fm_body is None:
        return {"hub": hub_path.name, "skipped": "no frontmatter"}
    fm, body = fm_body

    mode = fm.get("chronological_map_mode") or "curated"
    if mode != "derived":
        return {"hub": hub_path.name, "skipped": f"mode={mode}"}

    project_id = _hub_project_id(hub_path)
    members = list(_iter_member_notes(root, project_id))

    excluded_ids = list(fm.get("excluded_from_map") or [])
    excluded_reasons = list(fm.get("excluded_from_map_reasons") or [])
    excluded_set = set(excluded_ids)

    block_content = _render_block(members, excluded_set,
                                  excluded_reasons, excluded_ids)
    new_body, replace_mode = _replace_auto_block(body, block_content)

    return {
        "hub": hub_path.name,
        "project_id": project_id,
        "members": len(members),
        "visible": len([m for m in members
                        if str(m[1].get("id") or m[0].stem) not in excluded_set]),
        "excluded": len(excluded_ids),
        "replace_mode": replace_mode,
        "changed": new_body != body,
        "_old_body": body,
        "_new_body": new_body,
        "_fm": fm,
        "_path": hub_path,
    }


def _emit_diff(rec: dict) -> None:
    diff = difflib.unified_diff(
        rec["_old_body"].splitlines(keepends=True),
        rec["_new_body"].splitlines(keepends=True),
        fromfile=f"a/{rec['hub']}",
        tofile=f"b/{rec['hub']}",
        n=2,
    )
    sys.stdout.write("".join(diff))


def _apply(rec: dict) -> None:
    write_frontmatter(rec["_path"], rec["_fm"], rec["_new_body"])


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=None,
                        help="ZTN base path (defaults to repo_root() / 'zettelkasten').")
    parser.add_argument("--apply", action="store_true",
                        help="Write changes to disk. Without this flag, only diff is printed.")
    parser.add_argument("--hub", type=str, default=None,
                        help="Process a single hub by name (with or without .md). Default: all derived hubs.")
    args = parser.parse_args(argv)

    root = args.root or repo_root() / "zettelkasten"
    if not root.exists():
        print(f"ERROR: root does not exist: {root}", file=sys.stderr)
        return 1

    mocs = root / "5_meta" / "mocs"
    if args.hub:
        name = args.hub if args.hub.endswith(".md") else f"{args.hub}.md"
        hub_paths = [mocs / name]
        if not hub_paths[0].exists():
            print(f"ERROR: hub not found: {hub_paths[0]}", file=sys.stderr)
            return 1
    else:
        hub_paths = sorted(mocs.glob("hub-*.md"))

    summary = {
        "summary": True,
        "hubs_total": len(hub_paths),
        "hubs_processed": 0,
        "hubs_changed": 0,
        "hubs_skipped": 0,
        "applied": args.apply,
    }

    for hub_path in hub_paths:
        rec = _render_hub(hub_path, root)
        if rec is None:
            continue
        if "skipped" in rec:
            summary["hubs_skipped"] += 1
            print(json.dumps(
                {"hub": rec["hub"], "skipped": rec["skipped"]},
                ensure_ascii=False))
            continue
        summary["hubs_processed"] += 1
        if rec["changed"]:
            summary["hubs_changed"] += 1
        event = {k: v for k, v in rec.items() if not k.startswith("_")}
        print(json.dumps(event, ensure_ascii=False))
        if rec["changed"] and not args.apply:
            _emit_diff(rec)
        if args.apply and rec["changed"]:
            _apply(rec)

    print(json.dumps(summary, ensure_ascii=False), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
